version: '3.9'
services:

  testing_redis_auth:
    image: redis:6.2.6-alpine
    container_name: testing_redis_auth
    networks:
      - auth-network-tests

  testing_postgres_auth:
    image: postgres:13
    container_name: testing_postgres_auth
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${TEST_DB}
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
    networks:
      - auth-network-tests

  auth_api_tests:
    build:
      context: .
      dockerfile: tests.Dockerfile
    container_name: auth_api_tests
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=testing_postgres_auth
      - POSTGRES_DB=${TEST_DB}
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_PORT=${TEST_DB_PORT}
      - REDIS_HOST=testing_redis_auth
      - REDIS_PORT=${TEST_REDIS_PORT}
      - REDIS_DB=${TEST_REDIS_DB}
    depends_on:
      - testing_postgres_auth
      - testing_redis_auth
    networks:
      - auth-network-tests


networks:
  auth-network-tests:
    name: auth-network-tests
